#! /bin/bash

gcc -Wextra -Wall -Werror main.c ft_swap_top.c ft_initialise.c ft_push_top.c ft_swap_both_top.c ft_rotate.c ft_rotate_both.c ft_rotate_reverse.c ft_rotate_reverse_both.c ft_sort_min.c find_smallest.c ft_is_sorted.c ft_sort_big.c
